name: Deploy MyAPP
run-name: ${{ github.actor }} is deploying MyAPP 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-MyAPP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Config BackEnd file
        run: |
          sed -i 's/_USER_/${{ secrets.DB_USERNAME }}/g' backend/myapi.py
          sed -i 's/_PASSWORD_/${{ secrets.DB_PASSWORD }}/g' backend/myapi.py
          sed -i 's/_HOST_/${{ secrets.DB_HOST }}/g' backend/myapi.py
          sed -i 's/_DBNAME_/${{ secrets.DB_NAME }}/g' backend/myapi.py

      - name: Deploy BackEnd
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "backend/myapi.py"
          target: "/home/ubuntu/myapp/"
          strip_components: 1

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create Directory and Adjust Permissions
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.KEY }} << 'EOF'
            # Cria o diret贸rio se n茫o existir
            sudo mkdir -p /var/www/html/
            # Ajusta as permiss玫es do diret贸rio
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/
          EOF

      - name: Transfer and Untar Files
        run: |
          # Transferindo e descompactando o arquivo
          scp -i ~/.ssh/id_rsa GbCnDHMsrF.tar.gz ubuntu@<host>:/tmp/
          ssh -i ~/.ssh/id_rsa ubuntu@<host> << 'EOF'
            # Descompacta o arquivo no diret贸rio apropriado
            sudo tar -xzf /tmp/GbCnDHMsrF.tar.gz -C /var/www/html/
            # Remove o arquivo tar ap贸s a extra莽茫o
            sudo rm /tmp/GbCnDHMsrF.tar.gz
          EOF
        
      - name: Config FrontEnd file
        run: |
          sed -i 's/_API_ADDRESS_/${{ secrets.HOST }}/g' frontend/index.html

      - name: Deploy FrontEnd
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "frontend/index.html"
          target: "/var/www/html/"
          strip_components: 1
